global:
  nameOverride: "falcosight"
  adminUsername: "admin"
  adminPassword: "superuser_password"
  jwtSecret: "UEoFJp2LvR82WzMhIxZ3ViiTqWs8CuPmmP0CM5qhwzXhHwr8azL38Vyi9UNp2B5uEvHibyeoKHddFwiAQQZHoP"

backend:
  replicaCount: 1
  image:
    repository: falcosight-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  talonWebhookUrl: "http://falco-talon.falco-talon.svc.cluster.local:2803"

frontend:
  replicaCount: 1
  image:
    repository: falcosight-frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    hosts:
      - host: falcosight.ghosty-dashboard.com
        paths:
          - path: /
            pathType: Prefix

postgresql:
  enabled: true
  image:
    repository: timescale/timescaledb
    tag: "latest-pg15"
  database: "falcosight"
  username: "postgres"
  password: "postgrespassword"
  service:
    port: 5432
  persistence:
    enabled: false
    size: 8Gi
