apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: falcosight-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: falcosight-frontend
  template:
    metadata:
      labels:
        app: falcosight-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            - name: VUE_APP_BACKEND_URL # If using nginx env substitute or vite built-in
              value: "http://{{ .Release.Name }}-backend:{{ .Values.backend.service.port }}"
