{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: falcosight-postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
      name: tcp-postgresql
  selector:
    app: falcosight-postgresql
{{- end }}
