apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
data:
  ADMIN_USER: {{ .Values.global.adminUsername | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.global.adminPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | b64enc | quote }}
  
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ "" | b64enc | quote }}
  {{- end }}
