apiVersion: v1
kind: ServiceAccount
metadata:
  name: blast-radius-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blast-radius-admin-binding
subjects:
  - kind: ServiceAccount
    name: blast-radius-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: blast-radius-pod
  namespace: default
spec:
  serviceAccountName: blast-radius-admin
  containers:
    - name: test-container
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      # Această comandă va citi fișiere sensibile pentru a declanșa o alertă Falco ("Read sensitive file untrusted") (MITRE Credential Access)
      args: ["sleep 10; cat /etc/shadow; sleep 3600"]
      securityContext:
        privileged: true # Declanșează încălcări statice (manifest scanning)
